### PR TITLE
Models Updated (AuctionInfo, ItemData, SquadDetails)

### PR DESCRIPTION
**Pull request by hfielding**
Just a couple of changes for some JSON models.
Also updated the URL for club images.

I'm relatively new to pull requests so you might have to double check its all good.

### CODE REVIEW

**Comment by trydis** [comment]
Thanks, will take a look at it asap

**Comment by xtheokles** [comment]
Thanks! With this changes I could finally search a player on the market:)

**Comment by trydis** [comment]
Closed by accident, since i deleted the 2016 branch after i merged it into master.

**Comment by trydis** [comment]
Have you figured out what type `TradeOwner` should be? @xtheokles got `Error converting value {null} to type 'System.Boolean` https://github.com/trydis/FIFA-Ultimate-Team-Toolkit/issues/128#issuecomment-143012868. Should it be `bool?`?

**Comment by tringler** [comment]
@xtheokles Maybe you can add, that we don't use ```public static long CalculateBaseId(this long resourceId)``` anymore and adjust the ResourceID to AssetID for the GetItemInfo method.

**Comment by A-VORONKIN** [comment]
You should also add coinsProcessed to AuctionInfo. But I don`t know what type it should be. I just made it object.

**Comment by Spettacolo83** [comment]
I have just now (this afternoon worked well) the problem with PlaceBidAsync(auctionInfo, priceBuy)
The Exception is Internal Error.
I have added in AuctionInfo.cs the public bool? TradeOwner and public object CoinsProcessed.
Any suggestions?

**Comment by Spettacolo83** [comment]
Someperiods like now the function PlaceBidAsync(auctionInfo, priceBuy) returns an Exception: InternalServerError.
Have you the same issue?

**Comment by vhrustic** [comment]
@Spettacolo83  I've got the same problem. Have you managed to solve it?

**Comment by Spettacolo83** [comment]
Yes it's a temporary ban. Wait and modify your bot for disconnect or interrupt auto buyer after 30 min and reconnect after 5-10 min.

**Comment by trydis** [comment]
The changes have been merged, thanks @hfielding.

**Pull request closed without merging**
