### PR TITLE
Get Priceranges

### PR DESCRIPTION
**Pull request by tringler**
Gets the EA pricerange - You can only use this method right after you get tradepile / watchlist!

### CODE REVIEW

**Comment by trydis** [comment]
You're missing the actual changes, files changed = 0. Just push the changes to the same same branch (tringler:GetPriceRanges) and they will be added here automagically.

**Comment by tringler** [comment]
Sorry - Done :+1:

**Comment by trydis** [comment]
The changes from `FutRequestFactories` (`GetPriceRangesFactory`) are missing, it doesn't compile at the moment.

**Comment by tringler** [comment]
Sorry - How would be the best way to add it to this request?

**Comment by trydis** [comment]
No problem. Just add the missing code in a separate commit and push it to the same branch (tringler:GetPriceRanges).

**Comment by tringler** [comment]
I added with this commit, but it's not available on GitHub: https://github.com/tringler/FIFA-Ultimate-Team-Toolkit/commit/41cadc2108b8f0a6925c3412c293b71b55478345 - Does it need some replication time?

**Comment by trydis** [comment]
No, not in my experience. You have pushed the changes, not just committed them locally?

**Comment by tringler** [comment]
mhh :+1: - Really, using GitHub is rocket science!

**Comment by trydis** [comment]
Final step: https://github.com/trydis/FIFA-Ultimate-Team-Toolkit/issues/218

**Comment by trydis** [comment]
Merge into master, thanks.

**Pull request closed without merging**
