### PR TITLE
Updates for FIFA 17

### PR DESCRIPTION
**Pull request by trydis**
Plus some things that have been laying around for a while, such as:
- Captcha handling for companion app
- Open packs

### CODE REVIEW

**Comment by trydis** [comment]
[NuGet prerelease package](https://www.nuget.org/packages/UltimateTeam.Toolkit/3.1.0-dev48)

**Comment by trydis** [comment]
[NuGet prerelease package #2](https://www.nuget.org/packages/UltimateTeam.Toolkit/4.0.0-vnext0001)

GetItemAsync and GetPlayerImageAsync should hopefully be working now, let me know if not.

**Comment by kauefelipe** [comment]
@trydis u can´t use AssetId because some items (like contract) don't have this attribute defined.

Ex.
{
	"AssetId" : 0,
	"Assists" : 0,
	"AttributeList" : [],
	"CardSubTypeId" : 201,
	"Contract" : 0,
	"Dream" : false,
	"DiscardValue" : 3,
	"Fitness" : 0,
	"Formation" : "f433",
	"Id" : 259888084703,
	"InjuryGames" : 0,
	"InjuryType" : null,
	"ItemState" : "forSale",
	"ItemType" : "contract",
	"LastSalePrice" : 0,
	"LeagueId" : 0,
	"LifeTimeAssists" : 0,
	"Loans" : 0,
	"LifeTimeStats" : [],
	"LoyaltyBonus" : 0,
	"Morale" : 0,
	"Owners" : 1,
	"PlayStyle" : 0,
	"PreferredPosition" : null,
	"RareFlag" : 0,
	"Rating" : 50,
	"ResourceId" : -1874047191,
	"StatsList" : [],
	"Suspension" : 0,
	"TeamId" : 0,
	"Timestamp" : "1476670755",
	"Training" : 0,
	"Untradeable" : false,
	"Pile" : 5,
	"Nation" : 0,
	"CardAssetId" : 7,
	"Value" : 0,
	"Name" : null,
	"Category" : null,
	"MarketDataMaxPrice" : 5000,
	"MarketDataMinPrice" : 150,
	"WeightRare" : 0,
	"Bronze" : 8,
	"Silver" : 2,
	"Gold" : 1,
	"Amount" : 0,
	"FirstName" : null,
	"LastName" : null,
	"Negotiation" : null,
	"BioDescription" : null,
	"StadiumId" : 0,
	"Capacity" : 0,
	"Header" : null,
	"Year" : 0,
	"Manufacturer" : null,
	"Description" : null,
	"InternationalRep" : null
}

**Comment by trydis** [comment]
Ok, please send a PR.

I opened UT for the 1st time in over a year yesterday, to get the asset GUID. I was hoping someone else would contribute, since I'm not really interested in UT anymore. I'm sure there are several people out there with everything working correctly.

**Comment by kauefelipe** [comment]
To make "GetItem" works since last year i had added one "magical" number in "CalculateBaseId" to make it positive (someone talks in one topic about 2016 version and this works to me).
Do u want that i send a PR with this?

**Comment by kauefelipe** [comment]
No, he made same mistake of u. 
We can´t use the AssetId in some types of cards...

**Comment by trydis** [comment]
Yes, i took a closer look at the code last night and noticed it. It's a good idea, but it needs some changes. 

You mentioned it isn't only for players, so it should probably be named something else. 

Also, it's a property in the base class, but always used, so should probably be set in a constructor instead. As it is now, many people will most likely end up with null reference exceptions, because it hasn't been set. Exactly what happened in the PR which made the unit tests fail. 

Another i noticed is that it's impossible to not search for a specific player etc. now, although it 1st happened in 0a334235ba6d1bf0a0f4f55353d7f000dd9e6633, since definitionId or maskedDefId is always set. I should have noticed it back then and made both things possible.

If you could send the "magical" number and a short explanation it would be great, or a PR or create a [gist](https://gist.github.com/). Whatever works for you.

**Comment by kauefelipe** [comment]
Take a look #302 

Sorry if i did some wrong... i´m really newbie in Git!

**Comment by trydis** [comment]
Thanks @kauefelipe. Merged and pushed new package: https://www.nuget.org/packages/UltimateTeam.Toolkit/4.0.0-vnext0002

**Pull request merged**
