### PR TITLE
Special quality for players

### PR DESCRIPTION
**Pull request by A-VORONKIN**
Searching for Special (inform) players.

Example:

```
var searchParameters = new PlayerSearchParameters
{
    Page = 1,
    League = League.BarclaysPremierLeague,
    Team = Team.ManchesterUnited,
    Level = Level.Gold,
    Special = true
};
```

### CODE REVIEW

**Comment by tringler** [comment]
In my opinion it would be better to extend the Level enum, because in the WebApp you choose Bronze, Silver, Gold, Special - In Example if you choose `Level.Gold` and `Special = true` you would get a uri the original WebApp would not call.

I would do it like:
```
        private void SetLevel(ref string uriString)
        {
            switch (Level)
            {
                case Level.All:
                    break;
                case Level.Bronze:
                case Level.Silver:
                case Level.Gold:
                    uriString += "&lev=" + Level.ToString().ToLower();
                case Level.Special:
                    uriString += "&rare=SP";
                    break;
                default:
                    throw new ArgumentException("Level");
            }
        }
```

**Comment by A-VORONKIN** [comment]
Maybe you are right but in your case we can`t search only silver infrom players or only gold inform players.

**Comment by tringler** [comment]
Right - It is not possible in the WebApp and it should not be possible in the toolkit, but this is only my personal opinion.

**Comment by trydis** [comment]
I agree with @tringler, the toolkit shouldn't allow actions that aren't possible in the web app.

@A-VORONKIN: Will you be able to make the changes? If so, just push more commits to your branch `Special-quality-for-players` and they will appear here.

**Comment by A-VORONKIN** [comment]
Okay, no problem.

**Comment by tringler** [comment]
@A-VORONKIN I'm sorry for the delay of 18 months, but do you want to add your special level search feature to your code, because EA activated it in the meantime :)

**Comment by tringler** [comment]
No feedback for a month. I will close the PR.

**Pull request closed without merging**
