### PR TITLE
Get Definitions

### PR DESCRIPTION
**Pull request by tringler**
Gets all playercards (Standard, IF, SIF, TOTW,...) based on their Asset ID

### CODE REVIEW

**Comment by Lululuz** [comment]
This has to be added.
```c#
namespace UltimateTeam.Toolkit.Models
{
    public class ItemData
    {
         ...
         public bool Dream {  get; set; }
         ....
```
Anyway, I'm not able to search on the transfer market with the def. ID.
Eg. Marco Reus:
```
baseId = 188350
id = 50519998
```
If I now search by this ID I get this request
```
POST /ut/game/fifa16/transfermarket?start=0&num=13&maxb=99999999&maskedDefId=-1291657282&type=player HTTP/1.1
```
As you can see the maskedDefId is negative and will return no results.
Am I missing something or do you have the same issues?

**Comment by tringler** [comment]
But this should not be in my commit right?

```
namespace UltimateTeam.Toolkit.Models
{
    public class ItemData
    {
         ...
         public bool Dream {  get; set; }
         ....
```

I don't understand what you are doing exactly - You get the right ID from my method right? Why your marketsearch is using a negative ID then?

**Comment by Lululuz** [comment]
I downloaded v2.2.0-rc1 and got an JSON parsing error when calling
```
 var response = await _client.GetDefinitionsAsync(BaseID);
```
saying that Dream is missing blabla.

About the negative ID, this is how I've done the request. 

```
var searchParameters = new PlayerSearchParameters
                {
                    Page = 1,                    
                    ResourceId = 50519998L                    
                }; 
 var searchResponse = await _client.SearchAsync(searchParameters);
```
I hardcoded the resID to test it and it always uses a negative ID :/

**Comment by tringler** [comment]
I'm really sorry, but GitHub and I are not very good friends, but I'm learning. It should work now with the last 2 commits.

**Comment by Lululuz** [comment]
Thank you very much for your effort. :)

**Comment by tringler** [comment]
I made the big mistake and just downloaded the toolkit long time ago and developed some features into it. Now it's a bit difficult to split the whole new code into the different features. I will now use GitHub as designed to keep it easier.

**Comment by trydis** [comment]
Thanks for testing @Lululuz, will create a new prerelease with @tringler's changes.

**Comment by trydis** [comment]
Merge into master, thanks.

**Pull request closed without merging**
