### PR TITLE
Implementation of PinRequests

### PR DESCRIPTION
**Pull request by tringler**

### CODE REVIEW

**Comment by A-VORONKIN** [comment]
Mobile login is not working with it.

**Comment by tringler** [comment]
Pls get more in detail - It's running at my app with the Companion App.

**Comment by A-VORONKIN** [comment]
With current branch (without pull request) mobile login works fine. But with this branch
https://github.com/tringler/FIFA-Ultimate-Team-Toolkit/tree/PinRequests
it tells "Unable to login to WebApp" when I`m choosing Companion App. Login via Web App works fine.

**Comment by tringler** [comment]
I cannot verify at my client - Can you please debug it in LoginRequest.cs and tell me where exactly it breaks?

**Comment by A-VORONKIN** [comment]
Problem is in LoginMobileRequest.cs in Task<LoginResponse> PerformRequestAsync()
in this part
if (_loginDetails.SendPinRequests == true)
                {
                    var pinResponseCompanionAppAppOpened = await _pinEventRequestFactory(PinEventId.CompanionApp_AppOpened).PerformRequestAsync();
                }

I had Object reference not set an instance of an object. If I set sendPinRequest to false login is working fine.

**Comment by a7medit** [comment]
I can confirm that mobile login is not working.

**Comment by a7medit** [comment]
Turned out that i'm not sending the last parameter sendPinRequest.

**Comment by tringler** [comment]
I will take a look that evening - Thanks for your feedback

**Comment by a7medit** [comment]
Turned out that i did not send sendPinRequests parameter, but still you have to fix the app when you the overload method which dos not have the last parameter.

**Comment by tringler** [comment]
> Turned out that i did not send sendPinRequests parameter, but still you have to fix the app when you the overload method which dos not have the last parameter.


The sendPinRequests parameter is not mandatory - It's just if you want to disable the PinRequests. Surely you can set it to true but then it's the same as you don't set it at all.

**Comment by a7medit** [comment]
This's very strange case when i debug loginRequest returned _pinEventRequestFactory as null, but when you dive into _requestFactories.LoginRequestFactory and go step by step it return a value inside  _pinEventRequestFactory and everything are working.

**Comment by A-VORONKIN** [comment]
Still no fix for mobile login?

**Comment by tringler** [comment]
Should be fixed with https://github.com/trydis/FIFA-Ultimate-Team-Toolkit/pull/260/commits/17629013e0e835f1b03797b0c2b5f2fd041e8f64

**Comment by A-VORONKIN** [comment]
I had HttpRequestException very often when I`m using CompanionApp. I think that PinRequests wiil helps but it didn`t helps.

**Comment by tringler** [comment]
@A-VORONKIN Could it be you mean "ExpiredSession" - Try to wait about 5 seconds between each request - If not, please post the HTTP error codes - You should open a new issue, because it seems not touch this PR directly.

**Comment by A-VORONKIN** [comment]
@tringler  No, HttpRequestException. Message: Response status code does not indicate success.
https://gyazo.com/78a528afad81c18418dd58d9bea1f175

**Comment by mtdx** [comment]
@tringler can you please take a look apparently it failed some tests, this and the better handling of players ids. 

https://ci.appveyor.com/project/trydis/fifa-ultimate-team-toolkit/build/12/tests

**Comment by tringler** [comment]
My hope is @trydis fixes that error, so I don't have a clue how to fix - At the time I pushed that PR I was able to compile.

**Comment by mtdx** [comment]
well those are automated unit tests, nothing to do with compile, on a quick look, are related to exception handling, some functions doesn't throw the right exceptions.

**Comment by tringler** [comment]
@mtdx Any hint for me how I can debug this in the studio? I never have been used unit test so far.

**Comment by mtdx** [comment]
Well you need to work in the second project of this repo (UltimateTeam.Toolkit.Tests) you need to install some nuggets, but visual studio should auto-install for you, if you open this project I think,  eg. https://www.nuget.org/packages/NUnit/ , https://www.nuget.org/packages/Moq/

After that you run the tests and see which fails, then you debug as normal and fix, a nunit tests panel should show.

Tests should be self explanatory for example 

AssertEx.TaskThrows<ArgumentNullException>(async () => await _futClient.LoginAsync(null, null));

tests if LoginAsync Throws an ArgumentNullException exception when passed null arguments.

**Comment by trydis** [comment]
Will take a look at the remaining PRs during the next few days, have been AFK the entire weekend.

**Comment by bbday** [comment]
Do you have any stuck with pinrequest? like auctions, search or relist in trade pile?

**Comment by tringler** [comment]
I don't get you what you mean with stuck in that case

**Comment by mtdx** [comment]
what's going on with this? since is not in vnext I can't test it.

**Comment by tringler** [comment]
@trydis When you plan to merge to vnext?

**Comment by trydis** [comment]
@tringler: This PR and #261 cause several of the tests to fail, so I'll have to fix that first unless you can take a look at it? It would certainly help me a lot, as i would only need to review/merge.

**Comment by mtdx** [comment]
@tringler I would say to give up on #261 for now, I had quick look and it changes to many basic things that other stuff depends on, you can submit it later of course, after we merge all these pull requests.

**Comment by tringler** [comment]
I don't see that https://github.com/trydis/FIFA-Ultimate-Team-Toolkit/pull/261 is changing many basic things - It's just another handling of player ids - It even don't touch any web request

**Comment by mtdx** [comment]
even small changes like replacing a scalar with a model, can ripple through, but atm it seems that is holding things from moving on.

**Comment by tringler** [comment]
Just the unit tests needs to be fixed in this and in https://github.com/trydis/FIFA-Ultimate-Team-Toolkit/pull/261 PR

**Comment by trydis** [comment]
> I don't see that #261 is changing many basic things - It's just another handling of player ids - It even don't touch any web request

Correct, but it contains a backwards incompatible change (users must change their code after updating the lib), since `long ResourceId` is changed to `PlayerId PlayerId`. Even though the tests aren't up-to-date they failed, which is a good thing, since i'm trying to stick to [semantic versioning](http://semver.org/).

**Comment by tringler** [comment]
OK - Feel free to reject the PR

**Comment by trydis** [comment]
So you're not interested in adjusting the test code so behaves correctly after your changes?

Don't get me wrong, I really appreciate the PRs you're contributing. It's just a lot less work for me if the code compiles and the tests are green.

If you're not interesting in doing it i can do it, i just don't know when. Looking at the build logs it should only require some small changes.

**Comment by tringler** [comment]
I'm out - You know I'm thinking unit tests doesn't make sense if you don't control the API or webserver Whatever - Goodbye and Thank you for the fish! - Feel free to reject all my PRs

**Comment by tringler** [comment]
Yes, I will stop working on this repo. Thanks for your great work & effort on this project.

**Comment by trydis** [comment]
I understand, thanks for your contributions :smiley:

**Comment by A-VORONKIN** [comment]
@trydis when you will apply all this pull requests? I have some new requests but there is no sense to create them before you will apply current.

**Comment by losersFocus** [comment]
Besides not all tests running throuhg with this PR, is it working for some people?
@mtdx Do the PinRequests help out with banning of accounts in FUT17?

**Pull request closed without merging**
