### PR TITLE
Updated Nation.cs

### PR DESCRIPTION
**Pull request by CoverJ**
Added new Nations options and commented out removed/reassigned nations.

### CODE REVIEW

**Comment by CoverJ** [comment]
@trydis this is my first pull request so let me know if there's anything I have done incorrectly!

**Comment by trydis** [comment]
Thanks @CoverJ, would be great if you could delete the removed nations 👍 Just push another commit to the same branch and it will show up here.

Leagues would be appreciated too 😄

**Comment by A-VORONKIN** [comment]
You also need to update clubs.

**Comment by CoverJ** [comment]
@trydis sorry if this has become a bit of a mess but nations, leagues, and clubs should all be updated. I did it by scraping all the data from the FIFA 17 FUT DB. (https://www.easports.com/au/fifa/ultimate-team/fut/database) and then made a little program to go through and get all the unique nations/leagues/clubs, stripped out accented characters and replaced with just the english chars and then gave it a quick browse to make sure it all made sense, like i removed the "1. " from the beggining of some club names, changed cote d'ivoire to ivory coast etc.

I also added the little update from @kauefelipe in #305 so can search via filters rather than just resource id

Let me know if this needs modification!

**Comment by trydis** [comment]
Like @A-VORONKIN mentioned, the teams (which league they belong in) must be updated as well.

Right now the build has 409 errors because of the changed league values:
https://ci.appveyor.com/project/trydis/fifa-ultimate-team-toolkit/build/4.0.1-PullRequest.289+6.build.70#L1123

**Comment by CoverJ** [comment]
fixed in #309

**Pull request closed without merging**
