### PR TITLE
Login via Companion App

### PR DESCRIPTION
**Pull request by tringler**
Login via Companion App

### CODE REVIEW

**Comment by a7medit** [comment]
Mobile login not working with me.  {"Response status code does not indicate success: 400 (Bad Request).

**Comment by tringler** [comment]
You need to apply that fix:
[https://github.com/tringler/FIFA-Ultimate-Team-Toolkit/commit/7539363ee6565e58edc1512488a962a3bd48dda2](url)

Pls confirm you are not using your WebApp cookie to login  to companion app.

**Comment by a7medit** [comment]
No I'm not using WebApp cookie, and applied your fix but unfortunately did not worked, but i figured it out throw changing the last line in SkipAuthenticatorAdvertise function to be 

 _code = await authenticatorResponseMessage.Content.ReadAsStringAsync();
instead of 
var contentData = await authenticatorResponseMessage.Content.ReadAsStringAsync();

**Comment by tringler** [comment]
Thanks for feedback - I fixed it with an additional commit.

**Comment by a7medit** [comment]
Thanks a lot your solution is working with my temporarily banned account, do you recommend any RPM or number of requests are not a problem any more?.

**Comment by tringler** [comment]
I tested this night with the same RPM as WebApp without any problems. 40 RPM and 3 seconds between each request.

**Comment by tringler** [comment]
I forgot FUTClient and IFUTClient :( - I will provide an additional commit tonight.

**Comment by trydis** [comment]
Appreciate the effort @tringler, will take a look at the PR's tonight :+1:

**Comment by tringler** [comment]
I will post another commit into this branch - Pls wait for it before you merge

**Comment by tringler** [comment]
Ready to merge

**Comment by tringler** [comment]
Ready to merge.

**Comment by trydis** [comment]
Merged into the [vnext branch](https://github.com/trydis/FIFA-Ultimate-Team-Toolkit/commits/vnext)

**Comment by a7medit** [comment]
I cannot remove expired item or list item using webAPP, but everything working probably using CompanionApp.

**Comment by tringler** [comment]
I can confirm it :( I will take a look at it

**Comment by tringler** [comment]
@trydis - Maybe you can correct my mistake?

```
                AddMethodOverrideHeader(HttpMethod.Delete);
                AddCommonHeaders();
````

must be changed to:

```
                AddCommonHeaders();
                AddMethodOverrideHeader(HttpMethod.Delete);
````

If you call `AddCommonHeaders()` the headers will be reset - This is causing the issue. Almost all transactions are affected :-1:

**Comment by trydis** [comment]
I'll take a look at it

**Comment by tringler** [comment]
Found another typo here:

```
    internal class SearchRequest : FutRequestBase, IFutRequest<AuctionResponse>
    {
        private readonly SearchParameters _searchParameters;
        private AppVersion _appVersion;

        public SearchRequest(SearchParameters searchParameters)
        {
            searchParameters.ThrowIfNullArgument();
            _searchParameters = searchParameters;
        }

        public async Task<AuctionResponse> PerformRequestAsync(AppVersion appVersion)
        {
            _appVersion = appVersion;

            if (_appVersion == AppVersion.WebApp)
            {
                AddCommonHeaders();
                AddMethodOverrideHeader(HttpMethod.Get);
                var uriString = string.Format(Resources.FutHome + Resources.TransferMarket + "?start={0}&num={1}",
                (_searchParameters.Page - 1) * _searchParameters.PageSize, _searchParameters.PageSize + 1);
                _searchParameters.BuildUriString(ref uriString);

                var searchResponseMessage = await HttpClient
                    .PostAsync(uriString, new StringContent(" "))
                    .ConfigureAwait(false);

                return await Deserialize<AuctionResponse>(searchResponseMessage);
            }
            else if (_appVersion == AppVersion.CompanionApp)
            {
                AddCommonMobileHeaders();
                var uriString = string.Format(Resources.FutHome + Resources.TransferMarket + "?start={0}&num={1}",
                (_searchParameters.Page - 1) * _searchParameters.PageSize, _searchParameters.PageSize + 1);
                _searchParameters.BuildUriString(ref uriString);

                var searchResponseMessage = await HttpClient
                    .GetAsync(uriString + "&=" + DateTimeExtensions.ToUnixTime(DateTime.Now))
                    .ConfigureAwait(false);

                return await Deserialize<AuctionResponse>(searchResponseMessage);
            }
            else
            {
                return null;
            }
        }
    }
```

```
                var searchResponseMessage = await HttpClient
                    .GetAsync(uriString + "&=" + DateTimeExtensions.ToUnixTime(DateTime.Now))
                    .ConfigureAwait(false);
```

needs to be changed to:

```
                var searchResponseMessage = await HttpClient
                    .GetAsync(uriString + "&_=" + DateTimeExtensions.ToUnixTime(DateTime.Now))
                    .ConfigureAwait(false);
```

**Pull request closed without merging**
