### PR TITLE
FUT18

### PR DESCRIPTION
**Pull request by tringler**
Multiple adjustments and refactoring for migrating to FUT18

### CODE REVIEW

**Comment by tringler** [comment]
@trydis - Can you have a look if we can push it into master? Usually we should push into vnext at first, but the master branch is useless as long as it is on FUT17 code.

**Comment by trydis** [comment]
Sure @tringler, I'll take a look a bit later tonight

**Comment by trydis** [comment]
Ok, i'm just gonna merge this to master and then let's take it from there.

**Comment by trydis** [comment]
https://www.nuget.org/packages/UltimateTeam.Toolkit/5.0.0-rc0003

**Pull request merged**
