### PR TITLE
Get & Solve Captcha

### PR DESCRIPTION
**Pull request by tringler**
Get the Captcha as Base64 encoded image and solve it.

### CODE REVIEW

**Comment by tringler** [comment]
I forgot FUTClient and IFUTClient :( - I will provide an additional commit tonight.

**Comment by tringler** [comment]
Ready to merge.

**Comment by trydis** [comment]
Merged into the [vnext branch](https://github.com/trydis/FIFA-Ultimate-Team-Toolkit/commits/vnext)

**Comment by Extremeg** [comment]
At which region do you need to get the captcha? Captcha you only need if you will create an account?

**Comment by mtdx** [comment]
No, if you do to many RPMs captchas will pop up.

**Comment by Extremeg** [comment]
rpms ? sorry for the question

**Comment by mtdx** [comment]
requests per minute

**Comment by Extremeg** [comment]
ahh ok thanks

**Comment by Extremeg** [comment]
tringler do you can write me per : peter.nather@aol.de ?

**Pull request closed without merging**
