### PR TITLE
Added the POST to cancel the "authentication update" after login

### PR DESCRIPTION
**Pull request by lorenzh**

### CODE REVIEW

**Comment by trydis** [comment]
I guess only commit https://github.com/lorenzh/FIFA-Ultimate-Team-Toolkit/commit/db1c159ac2fec3171e913fe42fd09c4806afdcb8 is relevant, since the other just pulls stuff from my repository?

**Comment by lorenzh** [comment]
only lorenzh@db1c159 is relevent for the login

**Comment by trydis** [comment]
Yeah, noticed it shortly after, so i deleted the message :smile: Will look at merging it once i return from NDC London.

**Comment by trydis** [comment]
Merge into master, thanks.

**Pull request closed without merging**
